#ifndef ERRORS_H
#define ERRORS_H

#define NO_ERROR	0

// FEN errors
#define FEN_ILLEGAL_MISPLACED_PAWN			1
#define FEN_ILLEGAL_TOO_MANY_PAWNS			2
#define FEN_ILLEGAL_MISSING_WHITE_KING		3
#define FEN_ILLEGAL_MISSING_BLACK_KING		4
#define FEN_ILLEGAL_TOO_MANY_KINGS			5
#define FEN_ILLEGAL_TOO_MANY_PIECES         6
#define FEN_ILLEGAL_IN_CHECK                7
#define FEN_ILLEGAL_PAWN_ON_8TH             9
#define FEN_INVALID_SQUARE_COUNT			9
#define FEN_INVALID_UNKNOWN_PIECE       	10
#define FEN_INVALID_MISSING_SIDE_TO_MOVE	11
#define FEN_INVALID_MISSING_CASTLING_RIGHTS	12
#define FEN_INVALID_MISSING_EN_PASSANT		13

#endif
